version: 2
updates:
- package-ecosystem: npm
  directory: "/react_frontend"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swr
    versions:
    - 0.4.1
    - 0.5.0
    - 0.5.2
    - 0.5.5
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.8
    - 10.1.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
