name: Django Backend Tests

on:
  push:
    branches: [ main ]
    paths: [ "django_backend/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        
    defaults:
      run:
        working-directory: ./django_backend

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install pipenv && pipenv sync
    - name: Run Linter
      run: |
        pipenv run flake8
    - name: Run Tests
      run: |
        pipenv run ./manage.py test
        
