name: React Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    paths: [ "react_frontend/**" ]
    branches: [ main ]

jobs:
  react_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./react_frontend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run lint
      - run: npm run test:cover
      - run: npm run build

  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
